import type { ProjectFile } from '../types';

export interface Template { id: string; name: string; files: ProjectFile[]; }

const f = (path: string, content: string): ProjectFile => ({ path, content, size: new TextEncoder().encode(content).byteLength });

export const templates: Template[] = [
  { id: 'react-ts', name: 'React + TypeScript', files: [f('src/App.tsx', 'export default function App(){ return <main><h1>Hello SAYANOX</h1></main>; }\n'), f('src/main.tsx', "import { StrictMode } from 'react';\nimport { createRoot } from 'react-dom/client';\nimport App from './App';\ncreateRoot(document.getElementById('root')!).render(<StrictMode><App /></StrictMode>);\n"), f('README.md', '# React + TypeScript\n\nGenerated by SAYANOX FORGE.\n')] },
  { id: 'node-api', name: 'Node API', files: [f('src/server.ts', "import { createServer } from 'node:http';\ncreateServer((_req,res)=>{ res.writeHead(200, {'content-type':'application/json'}); res.end(JSON.stringify({ok:true})); }).listen(3000);\n"), f('README.md', '# Node API\n\nGenerated by SAYANOX FORGE.\n')] },
  { id: 'python-service', name: 'Python Service', files: [f('app.py', "from http.server import BaseHTTPRequestHandler, HTTPServer\n\nclass Handler(BaseHTTPRequestHandler):\n    def do_GET(self):\n        self.send_response(200); self.send_header('Content-Type','application/json'); self.end_headers(); self.wfile.write(b'{\"ok\": true}')\n\nHTTPServer(('127.0.0.1', 8000), Handler).serve_forever()\n"), f('README.md', '# Python Service\n\nGenerated by SAYANOX FORGE.\n')] },
  { id: 'static-web', name: 'Static Web', files: [f('index.html', '<!doctype html>\n<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SAYANOX</title></head><body><main><h1>Hello SAYANOX</h1></main></body></html>\n'), f('README.md', '# Static Web\n\nGenerated by SAYANOX FORGE.\n')] }
];

export function getTemplate(id: string): Template | undefined { return templates.find(t => t.id === id); }

export function downloadText(filename: string, content: string): void {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a'); a.href = url; a.download = filename; a.click();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
