import { useEffect, useMemo, useState, type ChangeEvent, type InputHTMLAttributes, type ReactNode } from 'react';
import { ShieldCheck, FolderOpen, Search, Terminal, Activity, FileCode2, AlertTriangle, Download, Package, History, Command, FileText, Filter, CheckCircle2, XCircle } from 'lucide-react';
import { analyzeFiles, healthScore, getSecurityRules } from './engine/analyzer';
import { demoFiles, readFileList } from './engine/files';
import { detectDependencies, detectLicenseHints } from './engine/dependencies';
import { getTemplate, downloadText } from './engine/project';
import { toMarkdown, toSarif, toJson, toHtml } from './engine/reports';
import { filterFindings, type ScanPolicy } from './engine/policy';
import type { ProjectFile, ScanResult, Severity } from './types';

const nav: Array<[string,string]> = [['dashboard','Dashboard'],['analyzer','Analyzer'],['security','Security'],['files','Files'],['generator','Generator']];
const severities: Severity[] = ['critical','high','medium','low','info'];
const directoryInputProps = { webkitdirectory: '', directory: '' } as unknown as InputHTMLAttributes<HTMLInputElement>;

export default function App(){
 const [section,setSection]=useState('dashboard'); const [files,setFiles]=useState<ProjectFile[]>(demoFiles); const [query,setQuery]=useState(''); const [palette,setPalette]=useState(false);
 const [enabledSeverities,setEnabledSeverities]=useState<Severity[]>([...severities]); const [ignoredRules,setIgnoredRules]=useState<string[]>([]); const [ignoredPaths,setIgnoredPaths]=useState(''); const [historyOpen,setHistoryOpen]=useState(false);
 const findings=useMemo(()=>analyzeFiles(files),[files]);
 const policy:ScanPolicy=useMemo(()=>({enabledSeverities:new Set(enabledSeverities),ignoredRules:new Set(ignoredRules),ignoredPaths:ignoredPaths.split(/\r?\n/).map(x=>x.trim()).filter(Boolean)}),[enabledSeverities,ignoredRules,ignoredPaths]);
 const visibleFindings=useMemo(()=>filterFindings(findings,policy),[findings,policy]); const score=healthScore(visibleFindings,files.length); const deps=useMemo(()=>detectDependencies(files),[files]); const licenses=useMemo(()=>detectLicenseHints(files),[files]);
 const filtered=visibleFindings.filter(f=>`${f.title} ${f.file} ${f.rule}`.toLowerCase().includes(query.toLowerCase()));
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setPalette(v=>!v)}if(e.key==='Escape')setPalette(false)};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[]);
 const load=async(e:ChangeEvent<HTMLInputElement>)=>{if(e.target.files?.length)setFiles(await readFileList(e.target.files));};
 const scan:ScanResult={findings:visibleFindings,files,score,scannedAt:new Date().toISOString()};
 const saveHistory=()=>{try{const old=JSON.parse(localStorage.getItem('sayanox-forge-history')||'[]') as ScanResult[];localStorage.setItem('sayanox-forge-history',JSON.stringify([scan,...old].slice(0,10)));setHistoryOpen(true)}catch{alert('Local history is unavailable in this browser.')}};
 const exportSarif=()=>downloadText('sayanox-forge.sarif',JSON.stringify(toSarif(visibleFindings),null,2)); const exportMd=()=>downloadText('sayanox-forge-report.md',toMarkdown(visibleFindings,score,files.length)); const exportJson=()=>downloadText('sayanox-forge-report.json',toJson(visibleFindings,score,files.length)); const exportHtml=()=>downloadText('sayanox-forge-report.html',toHtml(visibleFindings,score,files.length));
 return <div className="shell"><aside><div className="brand"><div className="logo">S</div><div><b>SAYANOX</b><span>FORGE</span></div></div><div className="nav">{nav.map(([id,label])=><button className={section===id?'active':''} onClick={()=>setSection(id)} key={id}>{id==='dashboard'?<Activity/>:id==='security'?<ShieldCheck/>:id==='files'?<FolderOpen/>:id==='analyzer'?<Search/>:<Terminal/>}{label}</button>)}</div><div className="sidecard"><small>LOCAL-FIRST · v0.2</small><strong>No API keys required</strong><span>Your source stays in this browser.</span></div></aside><main><header><div><small>DEVELOPER ENGINEERING WORKSPACE</small><h1>{nav.find(n=>n[0]===section)?.[1]}</h1></div><div className="actions"><button className="ghost" onClick={()=>setPalette(true)}><Command size={16}/> Ctrl K</button><label className="open"><FolderOpen size={17}/> Open project<input type="file" multiple {...directoryInputProps} onChange={load}/></label></div></header>{section==='dashboard'&&<Dashboard score={score} findings={visibleFindings.length} files={files.length} setSection={setSection} saveHistory={saveHistory} exportSarif={exportSarif} exportMd={exportMd} exportJson={exportJson} exportHtml={exportHtml} historyOpen={historyOpen} closeHistory={()=>setHistoryOpen(false)}/>} {section==='analyzer'&&<Analyzer files={files} findings={filtered} query={query} setQuery={setQuery} enabledSeverities={enabledSeverities} toggleSeverity={s=>setEnabledSeverities(v=>v.includes(s)?v.filter(x=>x!==s):[...v,s])} ignoredRules={ignoredRules} setIgnoredRules={setIgnoredRules} ignoredPaths={ignoredPaths} setIgnoredPaths={setIgnoredPaths}/>} {section==='security'&&<Security findings={visibleFindings} deps={deps.length} licenses={licenses.length}/>} {section==='files'&&<Files files={files}/>} {section==='generator'&&<Generator/>}</main>{palette&&<Palette close={()=>setPalette(false)} go={(s)=>{setSection(s);setPalette(false)}}/>}</div>
}
function Dashboard(p:{score:number;findings:number;files:number;setSection:(s:string)=>void;saveHistory:()=>void;exportSarif:()=>void;exportMd:()=>void;exportJson:()=>void;exportHtml:()=>void;historyOpen:boolean;closeHistory:()=>void}){return <><div className="hero"><div><span className="eyebrow">FORGE ENGINE v0.2</span><h2>Know your code.<br/><em>Ship with confidence.</em></h2><p>Static analysis, security policy, dependency discovery and reporting — entirely on-device.</p><button onClick={()=>p.setSection('analyzer')}>Run analysis <Search size={16}/></button></div><div className="score"><div>{p.score}</div><span>HEALTH SCORE</span></div></div><div className="cards"><Metric icon={<FileCode2/>} value={p.files} label="FILES SCANNED"/><Metric icon={<AlertTriangle/>} value={p.findings} label="ACTIVE FINDINGS"/><Metric icon={p.findings?<XCircle/>:<CheckCircle2/>} value={p.findings?'REVIEW':'PASS'} label="SECURITY STATUS"/></div><div className="panel"><h3>Reports & local history</h3><div className="quick-actions"><button onClick={p.saveHistory}><History size={16}/> Save scan</button><button onClick={p.exportSarif}><Download size={16}/> SARIF</button><button onClick={p.exportMd}><FileText size={16}/> Markdown</button><button onClick={p.exportJson}><Download size={16}/> JSON</button><button onClick={p.exportHtml}><FileText size={16}/> HTML</button></div>{p.historyOpen&&<HistoryPanel close={p.closeHistory}/>}</div></>}
function HistoryPanel({close}:{close:()=>void}){const [items,setItems]=useState<ScanResult[]>([]);useEffect(()=>{try{setItems(JSON.parse(localStorage.getItem('sayanox-forge-history')||'[]') as ScanResult[])}catch{setItems([])}},[]);return <div className="history"><div className="toolbar"><b>Recent local scans</b><button className="ghost" onClick={close}>Close</button></div>{items.length?items.map((x,i)=><div className="file-row" key={`${x.scannedAt}-${i}`}><History size={16}/><span>{new Date(x.scannedAt).toLocaleString()}</span><small>{x.score}/100 · {x.findings.length} findings</small></div>):<p className="muted">No saved scans yet.</p>}</div>}
function Metric({icon,value,label}:{icon:ReactNode;value:ReactNode;label:string}){return <div className="metric">{icon}<strong>{value}</strong><span>{label}</span></div>}
function Analyzer({findings,query,setQuery,files,enabledSeverities,toggleSeverity,ignoredRules,setIgnoredRules,ignoredPaths,setIgnoredPaths}:{findings:ReturnType<typeof analyzeFiles>;query:string;setQuery:(x:string)=>void;files:ProjectFile[];enabledSeverities:Severity[];toggleSeverity:(s:Severity)=>void;ignoredRules:string[];setIgnoredRules:(x:string[])=>void;ignoredPaths:string;setIgnoredPaths:(x:string)=>void}){return <div className="stack"><div className="toolbar"><div className="search"><Search size={16}/><input placeholder="Filter findings..." value={query} onChange={e=>setQuery(e.target.value)}/></div><span>{files.length} files · {findings.length} active findings</span></div><div className="policy"><div><b><Filter size={15}/> Severity filters</b><div className="chips">{severities.map(s=><button key={s} className={enabledSeverities.includes(s)?'chip active':'chip'} onClick={()=>toggleSeverity(s)}>{s}</button>)}</div></div><div><b>Ignored rules</b><input value={ignoredRules.join(', ')} onChange={e=>setIgnoredRules(e.target.value.split(',').map(x=>x.trim().toUpperCase()).filter(Boolean))} placeholder="SEC003, SEC005"/></div><div><b>Ignored path patterns</b><textarea value={ignoredPaths} onChange={e=>setIgnoredPaths(e.target.value)} placeholder={'dist/**\nnode_modules/**'}/></div></div>{findings.length===0?<Empty/>:<div className="finding-list">{findings.map(f=><div className={`finding ${f.severity}`} key={f.id}><div className="sev">{f.severity}</div><div><b>{f.title}</b><p>{f.message}</p><code>{f.rule} · {f.file}:{f.line}</code></div></div>)}</div>}</div>}
function Security({findings,deps,licenses}:{findings:ReturnType<typeof analyzeFiles>;deps:number;licenses:number}){const critical=findings.filter(f=>f.severity==='critical'||f.severity==='high');const rules=getSecurityRules();return <div className="stack"><div className="panel"><h3>Security & supply chain posture</h3><p className="muted">{rules.length} deterministic local rules. Advisory signals; production assurance still needs dedicated testing and review.</p><div className="security-grid"><div><strong>{critical.length}</strong><span>High priority</span></div><div><strong>{deps}</strong><span>Dependencies found</span></div><div><strong>{licenses}</strong><span>License hints</span></div><div><strong>{rules.length}</strong><span>Rules enabled</span></div></div></div><div className="panel"><h3>Security rule catalog</h3><div className="rule-grid">{rules.map(r=><div className="rule-card" key={r.id}><span>{r.id}</span><b>{r.title}</b><small>{r.severity}</small></div>)}</div></div></div>}
function Files({files}:{files:ProjectFile[]}){return <div className="panel"><h3>Project files ({files.length})</h3>{files.map(f=><div className="file-row" key={f.path}><FileCode2 size={17}/><span>{f.path}</span><small>{f.size} B</small></div>)}</div>}
function Generator(){const [selected,setSelected]=useState('');const template=selected?getTemplate(selected):undefined;const download=()=>{if(!template)return;const manifest=template.files.map(f=>`===== ${f.path} =====\n${f.content}`).join('\n\n');downloadText(`${template.id}-project.txt`,manifest)};return <div className="panel generator"><span className="eyebrow">PROJECT SCAFFOLDER</span><h3>Generate clean foundations</h3><p>Pick a deterministic template, preview its manifest, and export it without a server.</p><div className="templates">{[['react-ts','React + TypeScript'],['node-api','Node API'],['python-service','Python Service'],['static-web','Static Web']].map(([id,x])=><button key={id} onClick={()=>setSelected(id)} className={selected===id?'selected':''}>{x}<span>→</span></button>)}</div>{template&&<div className="preview"><b>{template.name}</b><pre>{template.files.map(f=>f.path).join('\n')}</pre><button onClick={download}><Package size={16}/> Export manifest</button></div>}</div>}
function Palette({close,go}:{close:()=>void;go:(s:string)=>void}){return <div className="overlay" onClick={close}><div className="palette" onClick={e=>e.stopPropagation()}><div className="palette-title"><Command size={18}/> Command palette</div>{nav.map(([id,label])=><button key={id} onClick={()=>go(id)}>{label}<kbd>↵</kbd></button>)}<button onClick={close}>Close <kbd>Esc</kbd></button></div></div>}
function Empty(){return <div className="empty"><ShieldCheck size={30}/><h3>No active findings</h3><p>The current policy and rule set found nothing actionable.</p></div>}
