import { useMemo, useState } from 'react';
import { ShieldCheck, FolderOpen, Search, Terminal, Activity, FileCode2, AlertTriangle, CheckCircle2 } from 'lucide-react';
import { analyzeFiles, healthScore } from './engine/analyzer';
import { demoFiles, readFileList } from './engine/files';
import type { ProjectFile } from './types';

const nav=[['dashboard','Dashboard'],['analyzer','Analyzer'],['security','Security'],['files','Files'],['generator','Generator']];
export default function App(){
 const [section,setSection]=useState('dashboard'); const [files,setFiles]=useState<ProjectFile[]>(demoFiles); const [query,setQuery]=useState('');
 const findings=useMemo(()=>analyzeFiles(files),[files]); const score=healthScore(findings,files.length);
 const filtered=findings.filter(f=>`${f.title} ${f.file} ${f.rule}`.toLowerCase().includes(query.toLowerCase()));
 const load=async(e:React.ChangeEvent<HTMLInputElement>)=>{if(e.target.files?.length)setFiles(await readFileList(e.target.files));};
 return <div className="shell"><aside><div className="brand"><div className="logo">S</div><div><b>SAYANOX</b><span>FORGE</span></div></div><div className="nav">{nav.map(([id,label])=><button className={section===id?'active':''} onClick={()=>setSection(id)} key={id}>{id==='dashboard'?<Activity/>:id==='security'?<ShieldCheck/>:id==='files'?<FolderOpen/>:id==='analyzer'?<Search/>:<Terminal/>}{label}</button>)}</div><div className="sidecard"><small>LOCAL-FIRST</small><strong>No API keys required</strong><span>Your source stays in this browser.</span></div></aside><main><header><div><small>DEVELOPER ENGINEERING WORKSPACE</small><h1>{nav.find(n=>n[0]===section)?.[1]}</h1></div><label className="open"><FolderOpen size={17}/> Open project<input type="file" multiple webkitdirectory="" onChange={load}/></label></header>{section==='dashboard'&&<Dashboard score={score} findings={findings.length} files={files.length} setSection={setSection}/>} {section==='analyzer'&&<Analyzer files={files} findings={filtered} query={query} setQuery={setQuery}/>} {section==='security'&&<Security findings={findings}/>} {section==='files'&&<Files files={files}/>} {section==='generator'&&<Generator/>}</main></div>
}
function Dashboard(p:{score:number;findings:number;files:number;setSection:(s:string)=>void}){return <><div className="hero"><div><span className="eyebrow">FORGE ENGINE v0.1</span><h2>Know your code.<br/><em>Ship with confidence.</em></h2><p>Static analysis, secret detection and project health — entirely on-device.</p><button onClick={()=>p.setSection('analyzer')}>Run analysis <Search size={16}/></button></div><div className="score"><div>{p.score}</div><span>HEALTH SCORE</span></div></div><div className="cards"><Metric icon={<FileCode2/>} value={p.files} label="FILES SCANNED"/><Metric icon={<AlertTriangle/>} value={p.findings} label="FINDINGS"/><Metric icon={<ShieldCheck/>} value={p.findings? 'REVIEW':'PASS'} label="SECURITY STATUS"/></div><div className="panel"><h3>Engineering principles</h3><div className="principles"><p><CheckCircle2/> Local by default</p><p><CheckCircle2/> Deterministic rules</p><p><CheckCircle2/> No telemetry</p><p><CheckCircle2/> Extensible plugins</p></div></div></>}
function Metric({icon,value,label}:{icon:React.ReactNode;value:React.ReactNode;label:string}){return <div className="metric">{icon}<strong>{value}</strong><span>{label}</span></div>}
function Analyzer({findings,query,setQuery,files}:{findings:ReturnType<typeof analyzeFiles>;query:string;setQuery:(x:string)=>void;files:ProjectFile[]}){return <div className="stack"><div className="toolbar"><div className="search"><Search size={16}/><input placeholder="Filter findings..." value={query} onChange={e=>setQuery(e.target.value)}/></div><span>{files.length} files · {findings.length} findings</span></div>{findings.length===0?<Empty/>:<div className="finding-list">{findings.map(f=><div className={`finding ${f.severity}`} key={f.id}><div className="sev">{f.severity}</div><div><b>{f.title}</b><p>{f.message}</p><code>{f.file}:{f.line}</code></div></div>)}</div>}</div>}
function Security({findings}:{findings:ReturnType<typeof analyzeFiles>}){let critical=findings.filter(f=>f.severity==='critical'||f.severity==='high');return <div className="panel"><h3>Security posture</h3><p className="muted">High-signal local checks designed for defensive code review. Findings are advisory, not a replacement for professional security testing.</p><div className="security-grid"><div><strong>{critical.length}</strong><span>High priority</span></div><div><strong>{findings.length}</strong><span>Total findings</span></div><div><strong>{findings.length? 'REVIEW':'CLEAR'}</strong><span>Recommended action</span></div></div></div>}
function Files({files}:{files:ProjectFile[]}){return <div className="panel"><h3>Project files</h3>{files.map(f=><div className="file-row" key={f.path}><FileCode2 size={17}/><span>{f.path}</span><small>{f.size} B</small></div>)}</div>}
function Generator(){return <div className="panel generator"><span className="eyebrow">PROJECT SCAFFOLDER</span><h3>Generate clean foundations</h3><p>Choose a template to create a deterministic file manifest in the browser.</p><div className="templates">{['React + TypeScript','Node API','Python Service','Static Web'].map(x=><button key={x} onClick={()=>alert(`${x} template selected — generation UI coming next.`)}>{x}<span>→</span></button>)}</div></div>}
function Empty(){return <div className="empty"><ShieldCheck size={30}/><h3>No findings</h3><p>The current rule set found nothing actionable.</p></div>}
